.PHONY: default
default: all

%:
	$(MAKE) -C basic_examples $@
	$(MAKE) -C batch_examples $@
	$(MAKE) -C query_examples $@
	$(MAKE) -C scan_examples $@
	$(MAKE) -C geospatial_examples $@

# Local Variables:
# mode: Makefile
# tab-width: 4
# indent-tabs-mode: t
# End:
# vim: tabstop=4:shiftwidth=4
